// KyleOS - Core Constants
// Platform identifiers, page types, and mode names

export const PLATFORM = {
  AGENT_TOOLS: 'AGENT_TOOLS',
  MLS: 'MLS',
  ONEHOME: 'ONEHOME',
  GMAIL: 'GMAIL',
  UNKNOWN: 'UNKNOWN'
};

export const PAGE_TYPE = {
  // Agent Tools
  CUSTOMER_DETAIL: 'CUSTOMER_DETAIL',
  EXPANDED_FOLLOW_UP_ROW: 'EXPANDED_FOLLOW_UP_ROW',
  TEAM_DASHBOARD: 'TEAM_DASHBOARD',
  APPOINTMENTS: 'APPOINTMENTS',
  FOLLOW_UPS: 'FOLLOW_UPS',
  PRIORITY_FOLLOW_UPS: 'PRIORITY_FOLLOW_UPS',
  PIPELINE_MINING: 'PIPELINE_MINING',
  TODAY_CALL_LIST: 'TODAY_CALL_LIST',
  RECENT_TOURERS: 'RECENT_TOURERS',
  CUSTOMERS_LIST: 'CUSTOMERS_LIST',
  DEALS: 'DEALS',
  CALENDAR: 'CALENDAR',
  PERFORMANCE: 'PERFORMANCE',
  HOME: 'HOME',

  // MLS
  MLS_LISTING: 'MLS_LISTING',
  MLS_SEARCH: 'MLS_SEARCH',
  MLS_COMPS: 'MLS_COMPS',

  // OneHome
  ONEHOME_CONTACTS: 'ONEHOME_CONTACTS',
  ONEHOME_SEARCH: 'ONEHOME_SEARCH',
  ONEHOME_LISTING: 'ONEHOME_LISTING',
  ONEHOME_COLLECTION: 'ONEHOME_COLLECTION',

  // Gmail
  GMAIL_INBOX: 'GMAIL_INBOX',
  GMAIL_THREAD: 'GMAIL_THREAD',
  GMAIL_COMPOSE: 'GMAIL_COMPOSE',

  UNKNOWN: 'UNKNOWN'
};

export const MODE = {
  AGENT_TOOLS: 'AGENT_TOOLS',
  KPI_FOLLOW_UP: 'KPI_FOLLOW_UP',
  TEAM_DASHBOARD_CAPTURE: 'TEAM_DASHBOARD_CAPTURE',
  MLS_LISTING: 'MLS_LISTING',
  MLS_SEARCH: 'MLS_SEARCH',
  CMA: 'CMA',
  ONEHOME: 'ONEHOME',
  FUB_CRM: 'FUB_CRM',
  GMAIL_PARSER: 'GMAIL_PARSER',
  CONTRACT_OFFER: 'CONTRACT_OFFER',
  MOBILE_ASSIST: 'MOBILE_ASSIST',
  IDLE: 'IDLE'
};

export const AUTO_ANALYZE_PAGE_TYPES = new Set([
  PAGE_TYPE.CUSTOMER_DETAIL,
  PAGE_TYPE.EXPANDED_FOLLOW_UP_ROW
]);

export const TEAM_SOURCE_PAGE_TYPES = new Set([
  PAGE_TYPE.TEAM_DASHBOARD,
  PAGE_TYPE.APPOINTMENTS,
  PAGE_TYPE.CUSTOMERS_LIST,
  PAGE_TYPE.PRIORITY_FOLLOW_UPS,
  PAGE_TYPE.PIPELINE_MINING,
  PAGE_TYPE.TODAY_CALL_LIST,
  PAGE_TYPE.RECENT_TOURERS
]);

export const REDFIN_EMAIL_BLOCK_DOMAIN = '@redfin.com';

export const APPROVED_ASSIGNEE = 'Kyle Kleinman';
